# Generated by Django 6.0.3 on 2026-03-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='experience',
            field=models.IntegerField(default=0, help_text='Years of experience'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
