# Generated by Django 6.0.3 on 2026-03-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_alter_trainerprofile_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
